### PR TITLE
Move dependencies from node modules to assets

### PR DESCRIPTION
**Pull request by aashishpsaini**
This PR serves two things:
- It moves the JS dependencies from node modules to assets
- Removes `webdrivers` gem (as it's not a required gem) and adds chromedriver in test workflow

- [x] The code follows the Activate Care development guidelines.
- [x] There are appropriate tests, preferring unit tests to system tests.
- [x] Performance related impacts have been considered.
- [x] Commit messages follow our conventions.
- [x] If there is a migration needed, I have performed a staging migration test and updated development.sql.

### CODE REVIEW

**Comment by aashishpsaini** [comment]
HI @jabbett Can you please review this PR and move it ahead. We need it for fixing an issue in our use case.

**Comment by canderson-activatecare** [comment]
- [ ] [Rails OWASP Checklist](https://www.notion.so/activatecare/OWASP-Top-Ten-Ruby-on-Rails-checklist-3460102fa3024d2db35e5503126b53c4?pvs=4) has been considered and no potential vulnerabilities found.

**Comment by canderson-activatecare** [comment]
Closing and re-opening to apply proper checks.

**Review by canderson-activatecare — APPROVED** [review]
Looks good, we'll capture Ruby upgrade in future issue so that we can rely on selenium chromedriver support.  For now will need to have chromedriver as a system resource.

**Comment by canderson-activatecare** [comment]
@imreACTmd bypassing merge block due to target branch not having PRCHECKLIST config.

**Review by canderson-activatecare — APPROVED** [review]

**Pull request merged**
